blank_issues_enabled: false
contact_links:
  - name: Documentação do projeto
    url: https://github.com/labican-ufrn/ativamente/tree/main/docs
    about: User Stories, plano de sprints e informações da equipe.
