// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo5EpLcM_8ZroypFum2ZyFWB7U5ELt-kA',
    appId: '1:684694620784:web:989ba6a2bad3e87ae5c2b5',
    messagingSenderId: '684694620784',
    projectId: 'ativamente-97e20',
    authDomain: 'ativamente-97e20.firebaseapp.com',
    storageBucket: 'ativamente-97e20.firebasestorage.app',
    measurementId: 'G-F8Q1NZKHYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQMI_7bKRDREMeSDHgO-apzN60JxEwYI8',
    appId: '1:684694620784:android:ff27852c1a6d6d17e5c2b5',
    messagingSenderId: '684694620784',
    projectId: 'ativamente-97e20',
    storageBucket: 'ativamente-97e20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-eVuO9lplBe1TSk9kcka2TK88JBwzHf4',
    appId: '1:684694620784:ios:6061dc447c9f51fae5c2b5',
    messagingSenderId: '684694620784',
    projectId: 'ativamente-97e20',
    storageBucket: 'ativamente-97e20.firebasestorage.app',
    iosBundleId: 'com.example.appAcademia',
  );
}
