// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRbIBk9LweOotDwoWCf4jHR1XIg9czACk',
    appId: '1:348791242172:web:b94c5646d395db7fd4bfb9',
    messagingSenderId: '348791242172',
    projectId: 'ativamente-estudo-nathan',
    authDomain: 'ativamente-estudo-nathan.firebaseapp.com',
    storageBucket: 'ativamente-estudo-nathan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Yw5HfwnZglxddGJguYYPqDbboytHy_A',
    appId: '1:348791242172:android:b48f8a5fbd27b0d5d4bfb9',
    messagingSenderId: '348791242172',
    projectId: 'ativamente-estudo-nathan',
    storageBucket: 'ativamente-estudo-nathan.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK1dnlxUaUA2YyW6mxx9GgOpYLAsPh9Vc',
    appId: '1:348791242172:ios:01ae32eb1b3aa17bd4bfb9',
    messagingSenderId: '348791242172',
    projectId: 'ativamente-estudo-nathan',
    storageBucket: 'ativamente-estudo-nathan.firebasestorage.app',
    iosBundleId: 'com.example.appAcademia',
  );
}
